### ISSUE TITLE
decompress-bzip throws error

### ISSUE THREAD

**Issue by determinate** [kevva/decompress-bzip2#1]
`var Decompress = require('decompress');
var bzip2 = require('decompress-bzip2');
var decompress = new Decompress()
	.src('123.tar.bz2')
	.dest('dest')
	.use(bzip2());
decompress.run(function (err, files) {
	if (err) {
		throw err;
	}
	console.log('Files extracted successfully!'); 
});`

throws below err
![image](https://cloud.githubusercontent.com/assets/15633523/17083261/a50d894c-51bb-11e6-8d3a-4fe451a4c774.png)
 So how what i must to do ?

**Comment by kevva** [comment]
It doesn't work with the newest version of `decompress` yet, use `decompress@3` instead.
